-- MySQL Script generated by MySQL Workbench
-- Tue Jul 4 16:38:44 2023
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SuperAlimentsPerou
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SuperAlimentsPerou` ;

-- -----------------------------------------------------
-- Schema SuperAlimentsPerou
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SuperAlimentsPerou` DEFAULT CHARACTER SET utf8 ;
USE `SuperAlimentsPerou` ;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`utilisateurs` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`utilisateurs` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NULL,
  `prenom` VARCHAR(150) NULL,
  `email` VARCHAR(250) NOT NULL,
  `hash` VARCHAR(250) NOT NULL,
  `tel` VARCHAR(20) NULL,
  `date_naissance` DATE NULL,
  `date_inscription` DATETIME NOT NULL,
  `token` VARCHAR(250) NULL,
  `date_validite_token` DATETIME NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`produits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`produits` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`produits` (
  `id_produit` INT NOT NULL AUTO_INCREMENT,
  `date_creation` DATETIME NOT NULL,
  `nom_produit` VARCHAR(250) NOT NULL,
  `description` TEXT NOT NULL,
  `prix_vente` DOUBLE NULL,
  PRIMARY KEY (`id_produit`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`photos` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`photos` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `url_photo` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`posts` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`posts` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(250) NOT NULL,
  `description` TEXT NOT NULL,
  `date_creation` DATETIME NOT NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`commentaires` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`commentaires` (
  `id_commentaire` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `id_post` INT NULL,
  `id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`id_commentaire`),
  CONSTRAINT `fk_commentaires_utilisateurs1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `SuperAlimentsPerou`.`utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaires_posts1`
    FOREIGN KEY (`id_post`)
    REFERENCES `SuperAlimentsPerou`.`posts` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`temoignages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`temoignages` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`temoignages` (
  `id_temoignage` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `id_photo` INT NULL,
  PRIMARY KEY (`id_temoignage`),
  CONSTRAINT `fk_temoignages_photos1`
    FOREIGN KEY (`id_photo`)
    REFERENCES `SuperAlimentsPerou`.`photos` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`mode_paiement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`mode_paiement` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`mode_paiement` (
  `id_mode_paiement` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `nom` VARCHAR(150) NOT NULL,
  `actif` TINYINT NOT NULL,
  PRIMARY KEY (`id_mode_paiement`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`mode_livraison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`mode_livraison` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`mode_livraison` (
  `id_mode_livraison` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `délai` VARCHAR(45) NOT NULL,
  `prix` INT NOT NULL,
  PRIMARY KEY (`id_mode_livraison`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`adresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`adresses` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`adresses` (
  `id_adresse` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(300) NOT NULL,
  `complement_adresse` VARCHAR(300) NOT NULL,
  `ville` VARCHAR(300) NOT NULL,
  `code_postal` VARCHAR(150) NOT NULL,
  `pays` VARCHAR(150) NOT NULL,
  `id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`id_adresse`),
  CONSTRAINT `fk_adresses_utilisateurs1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `SuperAlimentsPerou`.`utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SuperAlimentsPerou`.`commandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SuperAlimentsPerou`.`commandes` ;

CREATE TABLE IF NOT EXISTS `SuperAlimentsPerou`.`commandes` (
  `id_commande` INT NOT NULL AUTO_INCREMENT,
  `date_commande` DATETIME NOT NULL,
  `id_utilisateur` INT NOT NULL,
  `id_mode_paiement` INT NOT NULL,
  `id_mode_livraison` INT NOT NULL,
  `id_adresse` INT NOT NULL,
  PRIMARY KEY (`id_commande`),
  CONSTRAINT `fk_commandes_utilisateurs1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `SuperAlimentsPerou`.`utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_mode_paiement1`
    FOREIGN KEY (`id_mode_paiement`)
    REFERENCES `SuperAlimentsPerou`.`mode_paiement` (`id_mode_paiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_mode_livraison1`
    FOREIGN KEY (`id_mode_livraison`)
    REFERENCES `SuperAlimentsPerou`.`mode_livraison` (`id_mode_livraison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_adresses1`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `SuperAlimentsPerou`.`adresses` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
